//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public Alumno()
        {
            this.AlumnoCursoes = new HashSet<AlumnoCurso>();
        }
    
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public int ID_Alumno { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public decimal DNI { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<AlumnoCurso> AlumnoCursoes { get; set; }
    }
}
