//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoCurso
    {
        public AlumnoCurso()
        {
            this.Asistencias = new HashSet<Asistencia>();
        }
    
        public int Id_Alumno { get; set; }
        public int id_Curso { get; set; }
        public string Observaciones { get; set; }
        public string Profesor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual ICollection<Asistencia> Asistencias { get; set; }
    }
}
