//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.AlumnoCursoes = new HashSet<AlumnoCurso>();
        }
    
        public string Nombre_Curso { get; set; }
        public int ID_Curso { get; set; }
    
        public virtual ICollection<AlumnoCurso> AlumnoCursoes { get; set; }
    }
}
