//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_TPEntities : DbContext
    {
        public BD_TPEntities()
            : base("name=BD_TPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alumno> Alumnoes { get; set; }
        public DbSet<AlumnoCurso> AlumnoCursoes { get; set; }
        public DbSet<Asistencia> Asistencias { get; set; }
        public DbSet<Curso> Cursoes { get; set; }
    }
}
